name: Test coverage

on:
  push:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/documentation.yml"
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/documentation.yml"
    branches:
      - main

jobs:
  test_coverage:
    name: Test (Coverage)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test coverage
        run: yarn test:coverage
      - name: Upload to codecov
        uses: codecov/codecov-action@v3